-- Modified UPDATE statement with recurrence_weekly_days set to NULL

UPDATE public.event_details

SET id=4101, tenant_id='tenant_demo_002', title='New Year 2026', caption='New Year 2026 ', description='"Spark of Kerala," a showcase of performance arts and rhythm organized by MCEFEE, taking place in the USA from August to September 2025.  ΓÇó	Featured Artists: Swasika, Afsal, Mokksha, Akhila Anand, Veda Mithra, Sidhique Roshan, Kukku, Minnale Nazeer, Shiju, Vipin Kumar, Jojo Mathew, Suneeshmon.

ΓÇó	Contact Information: Booking contacts Sujith (+1 551-283-2437) and Arun (+1 551-221-1972), and email contactus@mcefee.org.

', start_date='2025-12-31', promotion_start_date='2025-11-19', end_date='2025-12-31', start_time='05:00 PM', end_time='09:00 PM', timezone='America/New_York', "location"='Breslin Performing Arts Center, 262 S Main St, Lodi, NJ 07644', directions_to_venue=NULL, capacity=300, admission_type='ticketed', is_active=true, max_guests_per_attendee=8, allow_guests=false, require_guest_approval=false, enable_guest_pricing=false, registration_deadline=NULL, cancellation_deadline=NULL, minimum_age=NULL, maximum_age=NULL, requires_approval=false, enable_waitlist=true, enable_qr_code=false, external_registration_url=NULL, email_header_image_url=NULL, created_by_id=NULL, event_type_id=3, created_at='2025-11-13 21:54:23.318', updated_at='2025-11-19 12:54:42.940', is_registration_required=false, is_sports_event=false, is_live=false, is_featured_event=false, featured_event_priority_ranking=0, live_event_priority_ranking=0, donation_metadata='{"isFundraiserEvent":false,"isCharityEvent":false}', event_recurrence_metadata='{"pattern":"DAILY","interval":1,"endType":"OCCURRENCES","occurrences":14}', is_recurring=true, recurrence_pattern='DAILY', recurrence_interval=1, recurrence_end_type='OCCURRENCES', recurrence_end_date=NULL, recurrence_occurrences=4, recurrence_weekly_days=NULL, recurrence_monthly_day=NULL, parent_event_id=NULL, recurrence_series_id=4101

WHERE id=4101 AND tenant_id='tenant_demo_002' AND title='New Year 2026' AND caption='New Year 2026 ' AND description='"Spark of Kerala," a showcase of performance arts and rhythm organized by MCEFEE, taking place in the USA from August to September 2025.  ΓÇó	Featured Artists: Swasika, Afsal, Mokksha, Akhila Anand, Veda Mithra, Sidhique Roshan, Kukku, Minnale Nazeer, Shiju, Vipin Kumar, Jojo Mathew, Suneeshmon.

ΓÇó	Contact Information: Booking contacts Sujith (+1 551-283-2437) and Arun (+1 551-221-1972), and email contactus@mcefee.org.

' AND start_date='2025-12-31' AND promotion_start_date='2025-11-19' AND end_date='2025-12-31' AND start_time='05:00 PM' AND end_time='09:00 PM' AND timezone='America/New_York' AND "location"='Breslin Performing Arts Center, 262 S Main St, Lodi, NJ 07644' AND directions_to_venue IS NULL AND capacity=300 AND admission_type='ticketed' AND is_active=true AND max_guests_per_attendee=8 AND allow_guests=false AND require_guest_approval=false AND enable_guest_pricing=false AND registration_deadline IS NULL AND cancellation_deadline IS NULL AND minimum_age IS NULL AND maximum_age IS NULL AND requires_approval=false AND enable_waitlist=true AND enable_qr_code=false AND external_registration_url IS NULL AND email_header_image_url IS NULL AND created_by_id IS NULL AND event_type_id=3 AND created_at='2025-11-13 21:54:23.318' AND updated_at='2025-11-19 12:54:42.940' AND is_registration_required=false AND is_sports_event=false AND is_live=false AND is_featured_event=false AND featured_event_priority_ranking=0 AND live_event_priority_ranking=0 AND donation_metadata='{"isFundraiserEvent":false,"isCharityEvent":false}' AND event_recurrence_metadata='{"pattern":"DAILY","interval":1,"endType":"OCCURRENCES","occurrences":14}' AND is_recurring=true AND recurrence_pattern='DAILY' AND recurrence_interval=1 AND recurrence_end_type='OCCURRENCES' AND recurrence_end_date IS NULL AND recurrence_occurrences=4 AND recurrence_weekly_days IS NULL AND recurrence_monthly_day IS NULL AND parent_event_id IS NULL AND recurrence_series_id=4101;

