/** Static download cards (legacy placeholders + real internal links). */
export const downloadsOldStaticItems: { title: string; link: string; image?: string }[] = [
  { title: 'local body Election winners award ceremony – Photos', link: '#', image: '/images/downloads/local_body_election.png' },
  { title: 'Catholicate Day Book Cover, Brochure', link: '#', image: '/images/downloads/catholictae_day.png' },
  { title: 'Panjangom', link: '#', image: '/images/downloads/panchangom.png' },
  { title: 'Download Photos', link: '/mosc-redesign/downloads-old/photos', image: '/images/downloads/download-photos.png' },
  { title: 'Medical Insurance', link: '#', image: '/images/downloads/medical_insurance.png' },
  { title: 'Kalpana', link: '/mosc-redesign/downloads-old/kalpana', image: '/images/downloads/kalpana.png' },
  { title: 'Covering Note to be submitted along with financial statements', link: '#' },
  { title: 'Church Financial Statements format for the year ended 31March 2025 of MOSC', link: '#', image: '/images/downloads/church_finance.png' },
  { title: 'Merit Evening 2025 Photos', link: '#', image: '/images/downloads/merit_evening.png' },
  { title: 'MALANKARA SABHA MAGAZINE', link: '#', image: '/images/downloads/malankara_magazine.jpg' },
  { title: 'EDUCATIONAL SPECIAL SCHOLARSHIP', link: '#' },
  { title: 'Merit Awards 2025', link: '#' },
  { title: 'Marriage Marga Nirdesha Form', link: '#' },
  { title: 'Budget format 2025-26', link: '#' },
  { title: 'GST', link: '#' },
  { title: 'Tenders', link: '#', image: '/images/downloads/tender.png' },
  { title: 'Merit Evening 2024 PHOTOS', link: '#', image: '/images/downloads/merit_evening_2024.png' },
  { title: 'Mega Quiz qualified list', link: '#', image: '/images/downloads/mega_quiz.png' },
  { title: 'Charge handing over/taking over Report for new Trustees and Secretary of the Parish', link: '#' },
  { title: 'Account Statement Format', link: '#', image: '/images/downloads/account_statement.png' },
  { title: 'അഖിലമലങ്കര മാർത്തോമൻ . പൈതൃക കലാസാഹിത്യ വൈജ്ഞാനിക മത്സരങ്ങൾ', link: '#', image: '/images/downloads/akhila_malankara_marthoman.jpg' },
  { title: 'Malankara Association (2022 – 2027)', link: '#', image: '/images/downloads/malankara_association.png' },
  { title: 'Panjangom 2023', link: '#', image: '/images/downloads/panjagom_2023.jpg' },
  { title: 'Panjangom 2022', link: '#', image: '/images/downloads/panjagom_2022.jpg' },
  { title: 'ASSOCIATION SECRETARY ELECTION', link: '#', image: '/images/logos/Current_Edits/MOSC-Logo-only.png' },
  { title: 'Catholicate Day 2022', link: '#', image: '/images/downloads/catholictae_day.png' },
  { title: 'Malankara Association 2022', link: '#', image: '/images/downloads/malankara_association.png' },
  { title: 'Application Forms', link: '/mosc-redesign/downloads-old/application-forms', image: '/images/downloads/application_forms.jpg' },
  { title: 'Malankara Association 2021', link: '#', image: '/images/downloads/malankara_association.png' },
  { title: 'prayer', link: '#', image: '/images/downloads/prayer.jpg' },
  { title: 'Advertisement', link: '#' },
  { title: 'FCRA Statements', link: '#', image: '/images/downloads/FCRA_statements.jpg' },
  { title: 'Pratheeshetha Prameyam', link: '#' },
  { title: 'Church Accounts Manual', link: '#', image: '/images/downloads/church_account_manual.jpg' },
  { title: 'Pdfs', link: '/mosc-redesign/downloads-old/pdfs', image: '/images/downloads/pdfs.jpg' },
  { title: 'Supreme Court Judgement, July 3, 2017', link: '#', image: '/images/downloads/supreme_court_judgement.jpg' },
  { title: 'Priest Directory', link: '#', image: '/images/downloads/priest_directory.jpg' },
  { title: 'Malankara Association : Association Secretary Election Final list 2017', link: '#', image: '/images/downloads/malankara_association.png' },
  { title: 'Malankara Association 2017 – Agenda & Nominated Members List', link: '#', image: '/images/downloads/malankara_association.png' },
  { title: 'Malankara Association Candidates Final List 2017', link: '#', image: '/images/downloads/malankara_association.png' },
  { title: 'Malankara Association Final list 2017', link: '#', image: '/images/downloads/malankara_association.png' },
  { title: 'Ministry of Human Empowernment', link: '#', image: '/images/downloads/ministry_human_empowerment.jpg' },
  { title: 'Guidelines for Preparing Church Accounts', link: '#', image: '/images/downloads/Guidelines_preparing_church_account.jpg' },
  { title: 'Prayer Books', link: '/mosc-redesign/downloads-old/prayer-books', image: '/images/downloads/prayer_books.jpg' },
  { title: 'Foreign Contributions', link: '#' },
  { title: 'Online Resourses', link: '#', image: '/images/downloads/online_resources.jpg' },
  { title: 'Photos', link: '/mosc-redesign/downloads-old/photos', image: '/images/downloads/photos.jpg' },
];
